name: cameratraps-classifier

channels:
- pytorch
- nvidia
- defaults
- conda-forge

dependencies:
- python>=3.7, <=3.11
- pytorch::pytorch
- pytorch::torchvision
- pytorch::pytorch-cuda=11.8
- Pillow
- humanfriendly
- ipywidgets
- jsonpickle
- jupyterlab
- matplotlib
- nb_conda_kernels
- networkx
- numpy
- openpyxl
- pandas
- progressbar2
- pylint
- python-graphviz
- scikit-learn
# Not used directly, but used by YOLOv5 imports
- seaborn
- tqdm
- xlrd
- pip

- pip:
  - azure-storage-blob
  - tensorboard